apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: lab-07
type: Opaque
stringData:
  DATABASE_PASSWORD: "postgres-password-123"
  JWT_SECRET: "jwt-secret-key-lab07"
  API_KEY: "api-key-lab07"
